### ISSUE TITLE
Impossible de récupérer/voir ce qu'il y à dans le coffre dépôt

### ISSUE THREAD

**Issue by PrinceSavage95** [Skulrag/esx_transistep_old#3]
Salut, je viens de mettre la ressource sur mon serveur, premièrement elle est top, et secondo j'ai une erreur quand j'essaye de voir le coffre du dépôt, donc j'arrive ni à prendre ni à déposer, puis dès que je clique sur « Prendre un objet dans le coffre », j'ai cette erreur:

SCRIPT ERROR: @esx_transistep/server/main.lua:103: attempt to index a nil value (local 'inventory')
> ref (@esx_transistep/server/main.lua:103)
> handler (@esx_addoninventory/server/main.lua:87)
> ref (@esx_transistep/server/main.lua:102)
> TriggerServerCallback (@es_extended/server/functions.lua:33)
> handler (@es_extended/server/common.lua:88)

Puis je voudrais savoir comment donner la permission aux recrues ainsi que transporteur (0 / 1 dans la sql) afin qu'ils achètent eux mêmes leurs véhicules ?

Merci !

**Comment by Skulrag** [comment]
Fixed :)

**Comment by LeonHartStrife** [comment]
Je viens de DL la dernière version du script en date et l'erreur est toujours présente : 

```
SCRIPT ERROR: @transistep/server/main.lua:106: attempt to index a nil value (local 'store')
> ref (@transistep/server/main.lua:106)
> handler (@esx_datastore/server/main.lua:80)
> ref (@transistep/server/main.lua:105)
> TriggerServerCallback (@es_extended/server/functions.lua:33)
> handler (@es_extended/server/common.lua:88)
```
