### ISSUE TITLE
Console spam SQL Errors

### ISSUE THREAD

**Issue by TheDjRider** [Skulrag/esx_transistep_old#6]
Hello, 
i saw 2 reports that console spam, one when new player join and other not shure when
one that is more often spam

> [ERROR] [MySQL] [esx_transistep] An error happens on MySQL for query "INSERT INTO `convoy_registered_list`(`identifier`, `is_trailer_stored`, `convoy_id`) VALUES ('steam:110000........', false, 0)": ER_DUP_ENTRY: Duplicate entry '0' for key 'PRIMARY'

**Comment by FALL1N1** [comment]
Purge your `convoy_registered_list` table.

**Comment by Skulrag** [comment]
Hi, dl the new sql file, I fixed it
