### ISSUE TITLE
items

### ISSUE THREAD

**Issue by lildevil1101** [Skulrag/esx_transistep_old#7]
we have the job working in our live server and we copied everything into our dev server but now its not working every time we try to view inventory in the warehouse of in the boss inventory but the job works fine except this part
![image](https://user-images.githubusercontent.com/78063618/105939151-d63f8980-6015-11eb-9325-36ef5eacae6e.png)

**Comment by pierrefasst** [comment]
V2 in draft. The script will now be adapted to the new ESX system and developped in JS.

**Comment by Skulrag** [comment]
I just started dev on fivem again, I gonna update asap the Fivem topic and this repository.
